---
title: Boston Tattoo Company
timezone: America/New_York
collections:
  artists:
    title: Artists
    output: true
  piercers:
    title: Piercers
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: artists
  values:
    main_image: ''
    profile_image: ''
    order: 1
    work_images: 
    layout: profile
- scope:
    path: ''
    type: piercers
  values:
    main_image: ''
    profile_image: ''
    order: 1
    work_images: 
    layout: profile
email: contact@bostontattoo.com
description: Established in December, 2004, the Boston Tattoo Company is the Boston
  area's most respected studio. We have been recognized by numerous Greater-Boston
  publications; such as The Phoenix, Somerville Scout, and Reader's Choice, as the
  best tattoo & body piercing studio!
baseurl: 
url: http://bostontattoo.com
consultation_url: https://form.jotform.com/90310530416140
markdown: kramdown
